services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.35.3
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
      - ./auth.json:/var/secrets/google/auth.json:ro
    restart: on-failure:0
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: "text2vec-google"
      USE_GOOGLE_AUTH: "true"
      GOOGLE_APPLICATION_CREDENTIALS: "/var/secrets/google/auth.json"

volumes:
  weaviate_data: